# Generated by Django 4.2.30 on 2026-05-05 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('nivel_minimo', models.CharField(blank=True, choices=[('5b', 'Quinta Baja'), ('5m', 'Quinta Media'), ('5a', 'Quinta Alta'), ('4b', 'Cuarta Baja'), ('4m', 'Cuarta Media'), ('4a', 'Cuarta Alta'), ('3b', 'Tercera Baja'), ('3m', 'Tercera Media'), ('3a', 'Tercera Alta'), ('2b', 'Segunda Baja'), ('2m', 'Segunda Media'), ('2a', 'Segunda Alta'), ('1b', 'Primera Baja'), ('1m', 'Primera Media'), ('1a', 'Primera Alta'), ('elite', 'Élite')], max_length=20)),
                ('max_jugadores', models.PositiveIntegerField(default=4)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('jugado', 'Jugado')], default='abierto', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_creados', to=settings.AUTH_USER_MODEL)),
                ('pista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='pistas.pista')),
            ],
            options={
                'ordering': ['-fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='JugadorPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmado', models.BooleanField(default=False)),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_unidos', to=settings.AUTH_USER_MODEL)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='partidos.partido')),
            ],
            options={
                'unique_together': {('partido', 'jugador')},
            },
        ),
    ]
