# Generated by Django 4.2.30 on 2026-05-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='nivel_minimo',
            field=models.CharField(choices=[('5b', 'Quinta Baja'), ('5m', 'Quinta Media'), ('5a', 'Quinta Alta'), ('4b', 'Cuarta Baja'), ('4m', 'Cuarta Media'), ('4a', 'Cuarta Alta'), ('3b', 'Tercera Baja'), ('3m', 'Tercera Media'), ('3a', 'Tercera Alta'), ('2b', 'Segunda Baja'), ('2m', 'Segunda Media'), ('2a', 'Segunda Alta'), ('1b', 'Primera Baja'), ('1m', 'Primera Media'), ('1a', 'Primera Alta'), ('elite', 'Élite')], max_length=20),
        ),
    ]
