# Generated by Django 4.2.30 on 2026-05-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0002_alter_partido_nivel_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='es_mixto',
            field=models.BooleanField(default=False, verbose_name='Partido mixto'),
        ),
    ]
