# Generated by Django 4.2.30 on 2026-05-06 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('torneos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_torneo', to=settings.AUTH_USER_MODEL)),
                ('pareja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_torneo_pareja', to=settings.AUTH_USER_MODEL)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='torneos.torneo')),
            ],
            options={
                'ordering': ['fecha_inscripcion'],
                'unique_together': {('torneo', 'jugador')},
            },
        ),
    ]
