# Generated by Django 4.2.30 on 2026-05-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0002_inscripciontorneo'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='hora_fin',
            field=models.TimeField(default='14:00'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='hora_inicio',
            field=models.TimeField(default='09:00'),
        ),
    ]
