# Generated by Django 4.2.30 on 2026-05-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0003_torneo_hora_fin_torneo_hora_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripciontorneo',
            name='pareja_apellido',
            field=models.CharField(blank=True, max_length=50, verbose_name='Apellido pareja (externa)'),
        ),
        migrations.AddField(
            model_name='inscripciontorneo',
            name='pareja_nombre',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nombre pareja (externa)'),
        ),
    ]
