# Generated by Django 4.2.30 on 2026-05-05 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, upload_to='monitores/')),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(limit_choices_to={'perfil__rol': 'monitor'}, on_delete=django.db.models.deletion.CASCADE, related_name='monitor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('max_alumnos', models.PositiveIntegerField(default=4)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='clases.monitor')),
                ('pista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='pistas.pista')),
            ],
            options={
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_clase', to=settings.AUTH_USER_MODEL)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='clases.clase')),
            ],
            options={
                'unique_together': {('clase', 'alumno')},
            },
        ),
    ]
