# Generated by Django 4.2.30 on 2026-05-05 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pistas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo', models.CharField(choices=[('simple', 'Simple'), ('recurrente', 'Recurrente')], default='simple', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('pista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='pistas.pista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ReservaRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(choices=[('semanal', 'Semanal')], default='semanal', max_length=20)),
                ('duracion', models.CharField(choices=[('6m', '6 Meses'), ('1a', '1 Año')], max_length=20)),
                ('fecha_fin', models.DateField()),
                ('reserva_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrentes', to='reservas.reserva')),
            ],
        ),
    ]
